export const products = [
  {
    id: 1,
    name: "Industrial Air Compressor",
    seller: "Machinery World",
    price: "₹1,25,000",
    category: "Industrial",
    rating: 4.8,
    reviews: 124,
    image: "https://loremflickr.com/500/500/compressor",
    orders: 450,
    badge: "Best Seller",
  },
  {
    id: 2,
    name: "Heavy Duty Welding Machine",
    seller: "WeldPower Systems",
    price: "₹18,500",
    category: "Industrial",
    rating: 4.6,
    reviews: 89,
    image: "https://loremflickr.com/500/500/welding",
    orders: 280,
    badge: null,
  },
  {
    id: 3,
    name: "Organic Cotton Yarn",
    seller: "Textile Hub",
    price: "₹450",
    category: "Fashion",
    rating: 4.9,
    reviews: 312,
    image: "https://loremflickr.com/500/500/yarn",
    orders: 1200,
    badge: "Top Rated",
  },
  {
    id: 4,
    name: "Solar Panel Monocrystalline",
    seller: "Green Energy Solutions",
    price: "₹12,000",
    category: "Electronics",
    rating: 4.7,
    reviews: 156,
    image: "https://loremflickr.com/500/500/solarpanel",
    orders: 560,
    badge: "Trending",
  },
  {
    id: 5,
    name: "Hydraulic Pump Unit",
    seller: "Fluid Tech",
    price: "₹35,000",
    category: "Industrial",
    rating: 4.5,
    reviews: 45,
    image: "https://loremflickr.com/500/500/hydraulicpump",
    orders: 120,
    badge: null,
  },
  {
    id: 6,
    name: "Polyester Fabric Roll",
    seller: "FabTex India",
    price: "₹120/m",
    category: "Raw Materials",
    rating: 4.4,
    reviews: 230,
    image: "https://loremflickr.com/500/500/fabric",
    orders: 3400,
    badge: "Popular",
  },
  {
    id: 7,
    name: "Microcontroller Board",
    seller: "Chipset Electronics",
    price: "₹450",
    category: "Electronics",
    rating: 4.8,
    reviews: 567,
    image: "https://loremflickr.com/500/500/microcontroller",
    orders: 890,
    badge: "New",
  },
  {
    id: 8,
    name: "Steel Pipes Schedule 40",
    seller: "Metal Works Corp",
    price: "₹85/kg",
    category: "Raw Materials",
    rating: 4.6,
    reviews: 67,
    image: "https://loremflickr.com/500/500/steelpipes",
    orders: 8900,
    badge: null,
  },
  {
    id: 9,
    name: "LED Display Screens",
    seller: "Visual Tech",
    price: "₹45,000",
    category: "Electronics",
    rating: 4.7,
    reviews: 178,
    image: "https://loremflickr.com/500/500/ledscreen",
    orders: 320,
    badge: null,
  },
];

export const allCategories = [
  "All",
  "Industrial",
  "Electronics",
  "Fashion",
  "Raw Materials",
  "Health & Beauty",
  "Apparel & Fashion",
  "Chemicals",
  "Machinery",
  "Construction & Real Estate",
  "Electronics & Electricity",
  "Hospital & Medical",
  "Gifts & Crafts",
  "Packaging & Paper",
  "Agriculture",
  "Home Supplies",
  "Mineral & Metals",
  "Industrial Supplies",
  "Pipes, Tubes & Fittings",
];

export const discountProducts = [
  {
    id: 101,
    name: "Premium Headphones Pro",
    price: "₹569",
    oldPrice: "₹875",
    discount: "-35%",
    image: "https://loremflickr.com/500/500/headphones",
    rating: 4.8,
    sold: 2340,
  },
  {
    id: 102,
    name: "Wireless Earbuds Elite",
    price: "₹685",
    oldPrice: "₹720",
    discount: "-5%",
    image: "https://loremflickr.com/500/500/earbuds",
    rating: 4.5,
    sold: 1560,
  },
  {
    id: 103,
    name: "Action Camera 4K Ultra",
    price: "₹548",
    oldPrice: "₹1826",
    discount: "-70%",
    image: "https://loremflickr.com/500/500/camera",
    rating: 4.9,
    sold: 890,
  },
  {
    id: 104,
    name: "Smart Watch Series X",
    price: "₹438",
    oldPrice: "₹999",
    discount: "-56%",
    image: "https://loremflickr.com/500/500/smartwatch",
    rating: 4.7,
    sold: 3200,
  },
  {
    id: 105,
    name: "Universal Phone Holder",
    price: "₹593",
    oldPrice: "₹714",
    discount: "-17%",
    image: "https://loremflickr.com/500/500/phoneholder",
    rating: 4.3,
    sold: 4500,
  },
  {
    id: 106,
    name: "Crystal Diamond Ring",
    price: "₹796",
    oldPrice: "₹1250",
    discount: "-36%",
    image: "https://loremflickr.com/500/500/diamondring",
    rating: 4.6,
    sold: 670,
  },
  {
    id: 107,
    name: "Bluetooth Speaker Bass",
    price: "₹423",
    oldPrice: "₹850",
    discount: "-50%",
    image: "https://loremflickr.com/500/500/speaker",
    rating: 4.4,
    sold: 1890,
  },
];

export const flashDeals = [
  {
    id: 201,
    name: "Designer Handbag",
    price: "₹1,499",
    oldPrice: "₹3,999",
    discount: "-62%",
    image: "https://loremflickr.com/500/500/handbag",
    rating: 4.9,
    stock: 12,
  },
  {
    id: 202,
    name: "Mechanical Keyboard RGB",
    price: "₹2,199",
    oldPrice: "₹4,500",
    discount: "-51%",
    image: "https://loremflickr.com/500/500/keyboard",
    rating: 4.8,
    stock: 8,
  },
  {
    id: 203,
    name: "Yoga Mat Premium",
    price: "₹449",
    oldPrice: "₹899",
    discount: "-50%",
    image: "https://loremflickr.com/500/500/yogamat",
    rating: 4.7,
    stock: 25,
  },
  {
    id: 204,
    name: "Electric Kettle Smart",
    price: "₹899",
    oldPrice: "₹1,799",
    discount: "-50%",
    image: "https://loremflickr.com/500/500/kettle",
    rating: 4.6,
    stock: 15,
  },
  {
    id: 205,
    name: "Portable Charger 20000mAh",
    price: "₹1,299",
    oldPrice: "₹2,599",
    discount: "-50%",
    image: "https://loremflickr.com/500/500/powerbank",
    rating: 4.5,
    stock: 30,
  },
  {
    id: 206,
    name: "Bluetooth Neckband Pro",
    price: "₹599",
    oldPrice: "₹1,299",
    discount: "-54%",
    image: "https://loremflickr.com/500/500/neckband",
    rating: 4.4,
    stock: 18,
  },
];

export const featuredProducts = [
  {
    id: 301,
    name: "Industrial CNC Machine",
    price: "₹85,000",
    category: "Machinery",
    seller: "Precision Tools India",
    verified: true,
    rating: 4.9,
    orders: 156,
    image: "https://loremflickr.com/500/500/machine",
  },
  {
    id: 302,
    name: "Organic Cotton Fabric Roll",
    price: "₹2,500/meter",
    category: "Textiles",
    seller: "Gujarat Textiles",
    verified: true,
    rating: 4.7,
    orders: 890,
    image: "https://loremflickr.com/500/500/fabric",
  },
  {
    id: 303,
    name: "Solar Panel 400W",
    price: "₹18,500",
    category: "Electronics",
    seller: "EcoEnergy Systems",
    verified: true,
    rating: 4.8,
    orders: 340,
    image: "https://loremflickr.com/500/500/solarpanel",
  },
  {
    id: 304,
    name: "Stainless Steel Pipes",
    price: "₹450/kg",
    category: "Industrial",
    seller: "Metro Steel Works",
    verified: true,
    rating: 4.6,
    orders: 2100,
    image: "https://loremflickr.com/500/500/steelpipes",
  },
];

export const sellers = [
  {
    id: "global-metals-co",
    name: "Global Metals Co.",
    tier: "Gold",
    verified: true,
    rating: 4.8,
    responseRate: "98%",
    responseTime: "< 2 hours",
    deliverySuccess: "99.5%",
    location: "Pune, Maharashtra",
    description:
      "Global Metals Co. is a premier supplier of high-grade industrial steel and components, serving clients worldwide since 2010.",
    joined: "2010",
    categories: ["Industrial", "Raw Materials"],
    banner: "https://loremflickr.com/1200/400/factory,industrial",
    logo: "https://loremflickr.com/200/200/logo,metal",
    certifications: ["ISO 9001:2015", "Export House Status", "Green Mfg"],
  },
  {
    id: "metro-steel-works",
    name: "Metro Steel Works",
    tier: "Silver",
    verified: true,
    rating: 4.6,
    responseRate: "95%",
    responseTime: "< 4 hours",
    deliverySuccess: "98%",
    location: "Mumbai, Maharashtra",
    description:
      "Metro Steel Works specializes in seamless pipes, tubes, and custom fittings for the construction and energy sectors.",
    joined: "2015",
    categories: ["Construction", "Pipes"],
    banner: "https://loremflickr.com/1200/400/construction,steel",
    logo: "https://loremflickr.com/200/200/logo,steel",
    certifications: ["ISO 9001"],
  },
  {
    id: "textile-hub",
    name: "Textile Hub",
    tier: "Gold",
    verified: true,
    rating: 4.9,
    responseRate: "99%",
    responseTime: "< 30 mins",
    deliverySuccess: "99.9%",
    location: "Surat, Gujarat",
    description:
      "Leading manufacturer and exporter of premium cotton yarns and synthetic fabrics.",
    joined: "2012",
    categories: ["Textiles", "Fashion"],
    banner: "https://loremflickr.com/1200/400/textile,fabric",
    logo: "https://loremflickr.com/200/200/logo,textile",
    certifications: ["GOTS Certified", "OEKO-TEX"],
  },
  {
    id: "ecoenergy-systems",
    name: "EcoEnergy Systems",
    tier: "Bronze",
    verified: true,
    rating: 4.5,
    responseRate: "90%",
    responseTime: "< 6 hours",
    deliverySuccess: "97%",
    location: "Bangalore, Karnataka",
    description:
      "Sustainable energy solutions provider specializing in solar panels and inverters.",
    joined: "2019",
    categories: ["Electronics", "Energy"],
    banner: "https://loremflickr.com/1200/400/solar,energy",
    logo: "https://loremflickr.com/200/200/logo,solar",
    certifications: ["Solar Keymark"],
  },
];
